export const SET_STATUS = 'SET_STATUS';

//account
export const SET_ACCOUNT_IDLE = 'SET_ACCOUNT_IDLE';
export const LOADING_GET_ACCOUNT = 'LOADING_GET_ACCOUNT';
export const GET_ACCOUNT_DONE = 'GET_ACCOUNT_DONE';
export const LOADING_GET_ACCOUNT_LOGIN = 'LOADING_GET_ACCOUNT_LOGIN';
export const GET_ACCOUNT_LOGIN_DONE = 'GET_ACCOUNT_LOGIN_DONE';
export const LOADING_GET_ACCOUNT_TEMP = 'LOADING_GET_ACCOUNT_TEMP';
export const GET_ACCOUNT_TEMP_DONE = 'GET_ACCOUNT_TEMP_DONE';
export const LOADING_ADD_ACCOUNT = 'LOADING_ADD_ACCOUNT';
export const ADD_ACCOUNT_DONE = 'ADD_ACCOUNT_DONE';
export const LOADING_ADD_ACCOUNT_TEMP = 'LOADING_ADD_ACCOUNT_TEMP';
export const ADD_ACCOUNT_TEMP_DONE= 'ADD_ACCOUNT_TEMP_DONE';
export const LOADING_CHECK_CONFIRMATION = 'LOADING_CHECK_CONFIRMATION';
export const CHECK_CONFIRMATION_DONE = 'CHECK_CONFIRMATION_DONE';
export const LOADING_SEND_CODE = 'LOADING_SEND_CODE';
export const SEND_CODE_DONE = 'SEND_CODE_DONE';
export const LOADING_ADD_FORGOT = 'LOADING_ADD_FORGOT';
export const ADD_FORGOT_DONE = 'ADD_FORGOT_DONE';
export const LOADING_RESET_PASSWORD = 'LOADING_RESET_PASSWORD';
export const RESET_PASSWORD_DONE = 'RESET_PASSWORD_DONE';
export const LOADING_LOGOUT = 'LOADING_LOGOUT';
export const LOGOUT_DONE = 'LOGOUT_DONE';
export const LOADING_CHECK_LOGIN = 'LOADING_CHECK_LOGIN';
export const CHECK_LOGIN_DONE = 'CHECK_LOGIN_DONE';


//FOLLOW
export const SET_FOLLOW_IDLE = 'SET_FOLLOW_IDLE';
export const LOADING_GET_FOLLOW = 'LOADING_GET_FOLLOW';
export const GET_FOLLOW_DONE = 'GET_FOLLOW_DONE';
export const LOADING_ADD_FOLLOW = 'LOADING_ADD_FOLLOW';
export const ADD_FOLLOW_DONE = 'ADD_FOLLOW_DONE';
export const LOADING_DELETE_FOLLOW = 'LOADING_DELETE_FOLLOW';
export const DELETE_FOLLOW_DONE = 'DELETE_FOLLOW_DONE';
export const LOADING_UPDATE_FOLLOW = 'LOADING_UPDATE_FOLLOW';
export const UPDATE_FOLLOW_DONE = 'UPDATE_FOLLOW_DONE';


//BOOKMARK
export const SET_BOOKMARK_IDLE = 'SET_BOOKMARK_IDLE';
export const LOADING_GET_BOOKMARK_IDS = 'LOADING_GET_BOOKMARK_IDS';
export const GET_BOOKMARK_IDS_DONE = 'GET_BOOKMARK_IDS_DONE';
export const LOADING_GET_BOOKMARK = 'LOADING_GET_BOOKMARK';
export const LOADING_GET_BOOKMARK_NEXT = 'LOADING_GET_BOOKMARK_NEXT';
export const GET_BOOKMARK_DONE = 'GET_BOOKMARK_DONE';
export const LOADING_ADD_BOOKMARK = 'LOADING_ADD_BOOKMARK';
export const ADD_BOOKMARK_DONE = 'ADD_BOOKMARK_DONE';
export const LOADING_DELETE_BOOKMARK = 'LOADING_DELETE_BOOKMARK';
export const DELETE_BOOKMARK_DONE = 'DELETE_BOOKMARK_DONE';


//EVENT
export const SET_EVENT_IDLE = 'SET_EVENT_IDLE';
export const LOADING_ADD_EVENT = 'LOADING_ADD_EVENT';
export const ADD_EVENT_DONE = 'ADD_EVENT_DONE';


//HOME
export const SET_HOME_REFRESH = 'SET_HOME_REFRESH';
export const SET_HOME_IDLE = 'SET_HOME_IDLE';
export const LOADING_GET_HOME = 'LOADING_GET_HOME';
export const LOADING_GET_HOME_NEXT = 'LOADING_GET_HOME_NEXT';
export const GET_HOME_DONE = 'GET_HOME_DONE';


//UNIT 
export const SET_UNIT_IDLE = 'SET_UNIT_IDLE';
export const LOADING_GET_UNIT = 'LOADING_GET_UNIT';
export const GET_UNIT_DONE = 'GET_UNIT_DONE';

